### ISSUE TITLE
[BUG] [GUI] Uncatch Error: AttributeError: 'NoneType' object has no attribute 'width'

### ISSUE THREAD

**Issue by MC-ALL** [pur1fying/blue_archive_auto_script#241]
### First Bad Commit
N/A

### Problem description & steps to reproduce
1. Add a new profile, **don't restart**
2. Click `Dailies` icon on the left side
3. Click any Card item on this page
4. Crash

### Relevant log output
```shell
Traceback (most recent call last):
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/gui/components/template_card.py", line 227, in mousePressEvent
    self._trigger_expand()
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/gui/components/template_card.py", line 232, in _trigger_expand
    rename_dialog = DialogSettingBox(self.config.get_window(), self.config, pop_layout,
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/gui/util/customed_ui.py", line 171, in __init__
    super().__init__(parent)
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/env/lib/python3.9/site-packages/qfluentwidgets/components/dialog_box/message_box_base.py", line 19, in __init__
    super().__init__(parent=parent)
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/env/lib/python3.9/site-packages/qfluentwidgets/components/dialog_box/mask_dialog_base.py", line 22, in __init__
    self.setGeometry(0, 0, parent.width(), parent.height())
AttributeError: 'NoneType' object has no attribute 'width'
[1]    123651 IOT instruction (core dumped)  /home/circuitx/Work/baas_dev/blue_archive_auto_script/env/bin/python 
```
